version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      # Install poetry
      - pip install poetry
      # Don't use virtualenvs with poetry
      - poetry config virtualenvs.create false

# Build documentation in the source/ directory with Sphinx
sphinx:
  configuration: source/conf.py

# Python requirements for building the docs
python:
  install:
    - method: "pip"
      path: .

# Additional formats of docs to build
formats:
  - pdf
  - epub 